## Topic: Vector Shape Basics
Understand how a 1D NumPy array stores elements and reports shape.

In [1]:
import numpy as np
v = np.array([1,2,3,4])
print(v.shape)

(4,)


## Topic: Matrix Shape Basics
Learn shape representation for 2D arrays as rows and columns.

In [2]:
M = np.array([[1,2,3],[4,5,6]])
print(M.shape)

(2, 3)


## Topic: Tensor Shape for Image Batches
Inspect a 4D tensor that mimics mini-batches of RGB images.

In [3]:
images = np.random.rand(32, 224, 224, 3 )
print(images.shape)

(32, 224, 224, 3)


## Topic: Matrix Addition
Perform element-wise addition between matrices of the same shape.

In [4]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[7,8],[9,10],[11,12]])
C = A + B
print(C)

[[ 8 10]
 [12 14]
 [16 18]]


## Topic: Scalar Multiplication
Scale every element in a matrix by a constant.

In [5]:
A = np.array([[1,2],[3,4],[5,6]])
C = 2 * A
print(C)

[[ 2  4]
 [ 6  8]
 [10 12]]


## Topic: Matrix Multiplication
Compute matrix product using the @ operator or matmul semantics.

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.matmul(A, B)
print(C)

[[19 22]
 [43 50]]


## Topic: Matrix Transpose
Swap rows and columns using the transpose operation.

In [8]:
A = np.array([[1,2,3],[4,5,6]])
A_T = A.T
print(A_T)
print(A_T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


## Topic: Dot Product
Measure vector alignment and combined magnitude with a dot product.

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
dot_product = np.dot(a, b)
print(dot_product)

32


## Topic: Identity Matrix
Create an identity matrix used in many linear algebra operations.

In [10]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Topic: Matrix Inverse
Compute the inverse of a square matrix and verify with multiplication.

In [11]:
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
print(A @ A_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Topic: Vector Norms
Compare L1 and L2 norms as measures of vector size.

In [12]:
v = np.array([3, 4])
l2_norm = np.linalg.norm(v, 2)
l1_norm = np.linalg.norm(v, 1)
print(f"L2 norm: {l2_norm}")
print(f"L1 norm: {l1_norm}")

L2 norm: 5.0
L1 norm: 7.0


## Topic: Eigenvalues and Eigenvectors
Decompose a matrix into eigenvalues and corresponding eigenvectors.

In [13]:
A = np.array([[4, 1], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


## Topic: Matrix Rank
Check linear independence information through matrix rank.

In [14]:
A = np.array([[1, 2] , [2, 4]])
rank = np.linalg.matrix_rank(A)
print(f"Rank: {rank}")

Rank: 1


## Topic: Linear Regression with Normal Equation
Solve for linear model weights in closed form.

In [16]:
import numpy as np

# X: input (n_samples, n_features)
X = np.array([[1, 1], [1, 2], [1, 3], [1, 4]], dtype=float)

# y: target (n_samples,)
y = np.array([2, 3, 4, 5], dtype=float)

w = np.linalg.inv(X.T @ X) @ X.T @ y
predictions = X @ w

print("weights:", w)
print("predictions:", predictions)

weights: [1. 1.]
predictions: [2. 3. 4. 5.]


## Topic: Forward Pass and ReLU Activation
Build a simple neural network layer and apply ReLU nonlinearity.

In [17]:
X = np.random.rand(32, 10)
W = np.random.rand(10, 5)
b = np.random.rand(5)

hidden = X @ W + b
output = np.maximum(0, hidden)
print("Hidden layer output:\n", hidden)
print("Activated output:\n", output)

Hidden layer output:
 [[1.87865701 2.35326967 2.17956643 2.03117468 1.04661493]
 [3.57465875 3.46181001 3.49723984 3.49560792 2.18798541]
 [3.8130082  3.28364132 3.69033506 3.63491538 2.74835729]
 [2.79794911 2.70344844 3.35224055 3.18840202 1.96270397]
 [2.27015948 2.76142955 2.44652297 2.2275977  0.90494567]
 [3.01791805 3.71648897 3.74655056 3.52311794 1.96638808]
 [2.95059791 3.20084761 3.01329361 2.91682041 1.6065932 ]
 [3.34976534 3.80063943 4.03428762 4.31095242 1.95543801]
 [2.95694711 4.02536293 3.68720679 3.93459893 1.55791219]
 [3.00719322 3.04588532 3.34360139 3.13258835 1.60084662]
 [2.20947939 3.0686971  2.60249864 2.53497998 1.53011054]
 [2.69745836 3.05447143 2.61704938 2.76193017 1.00683718]
 [3.19990286 3.0370995  3.17328051 3.39425127 2.10804328]
 [3.31684413 4.12075632 3.63482182 3.53664347 1.70635659]
 [1.87987133 2.82072525 2.12296925 2.34723474 1.23023682]
 [2.59000523 2.79377135 2.80963268 2.444016   1.62021444]
 [2.15511239 2.63631508 3.47375039 2.90351536 1.94

## Topic: Principal Component Analysis
Reduce feature dimensions using manual PCA steps and sklearn PCA.

In [18]:
from sklearn.decomposition import PCA

#Manually
X_centered = X - X.mean(axis=0)
cov_matrix = (X_centered.T @ X_centered) / len(X)
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Top 2 components
X_pca = X_centered @ eigenvectors[:, :2]

# Or using sklearn

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print("PCA result:\n", X_pca)

PCA result:
 [[-0.30266889 -0.11877001]
 [ 0.60087681  0.08688818]
 [ 0.03110867  0.83338399]
 [ 0.14561595  0.3744973 ]
 [ 0.15037114 -0.69806917]
 [ 0.41836799 -0.29702501]
 [-0.16232689 -0.18816197]
 [-0.17078636  0.44894853]
 [-0.46390378 -0.10450799]
 [ 0.48237013  0.01832428]
 [ 0.23674932 -0.60977158]
 [-0.29294343 -0.58937172]
 [ 0.21949778 -0.00232659]
 [-0.36700698 -0.09560471]
 [-0.38284657 -0.64009198]
 [ 0.57751287 -0.22053646]
 [ 0.36307339  0.1376722 ]
 [ 0.29307567 -0.00706613]
 [-0.36466068  0.60497198]
 [-0.2126939  -0.1945624 ]
 [ 0.23050862 -0.27624905]
 [ 1.00376737  0.54821811]
 [ 0.46106178 -0.33286378]
 [-0.37009496  0.11525061]
 [ 0.25610421  0.1468205 ]
 [-0.59199733  0.13959874]
 [-0.37386066  0.60190954]
 [-0.51563919  0.11809258]
 [-0.54035514 -0.10272739]
 [ 0.5512759   0.12881383]
 [-0.28891581  0.06731648]
 [-0.62063703  0.10699908]]


## Topic: Cosine Similarity
Compare manual and sklearn cosine similarity implementations.

In [20]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def cosine_similarity_manual(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

vec_a = np.array([1, 2, 3], dtype=float)
vec_b = np.array([4, 5, 6], dtype=float)

sim_manual = cosine_similarity_manual(vec_a, vec_b)
sim_sklearn = cosine_similarity([vec_a], [vec_b])[0][0]

print(f"Manual cosine similarity: {sim_manual}")
print(f"Sklearn cosine similarity: {sim_sklearn}")

Manual cosine similarity: 0.9746318461970762
Sklearn cosine similarity: 0.9746318461970762


## Topic: Gradient Descent for Linear Regression
Optimize linear model weights iteratively using gradients.

In [22]:
import numpy as np

# Simple gradient descent
X_gd = np.array([[1, 1], [1, 2], [1, 3], [1, 4]], dtype=float)
y_gd = np.array([2, 3, 4, 5], dtype=float)

w_gd = np.zeros(X_gd.shape[1], dtype=float)
learning_rate = 0.01

for epoch in range(1000):
    predictions = X_gd @ w_gd
    error = predictions - y_gd
    gradient = X_gd.T @ error / len(X_gd)
    w_gd -= learning_rate * gradient

print("Learned weights:", w_gd)
print("Final predictions:", X_gd @ w_gd)

Learned weights: [0.86777362 1.04497309]
Final predictions: [1.91274671 2.95771981 4.0026929  5.04766599]


## Topic: Broadcasting in NumPy
Use shape expansion rules to combine arrays of different shapes.

In [23]:
A = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20, 30])

C = A+ b # b is broadcasted to match A's shape
print(C)

[[11 22 33]
 [14 25 36]]


## Topic: Reshaping and Flattening Arrays
Change array dimensions for model input formatting and recovery.

In [24]:
X = np.array([1, 2, 3, 4, 5, 6])

X_2d = X.reshape(2, 3)
# [[1, 2, 3],
#  [4, 5, 6]]

X_3d = X.reshape(2, 3, 1)

# Flatten back
X_flat = X_2d.flatten() 

## Topic: Axis-Wise Aggregations
Compute sums, means, max, and min along rows or columns with axis.

In [26]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Sum along axis 0 (down rows)
col_sums = X.sum(axis=0)  # [5, 7, 9]

# Sum along axis 1 (across columns)
row_sums = X.sum(axis=1)  # [6, 15]

# Mean, max, min work similarly
col_means = X.mean(axis=0)
col_maxes = X.max(axis=0)
col_mins = X.min(axis=0)

print("Column sums:", col_sums)
print("Row sums:", row_sums)
print("Column means:", col_means)
print("Column maxes:", col_maxes)
print("Column mins:", col_mins)

Column sums: [5 7 9]
Row sums: [ 6 15]
Column means: [2.5 3.5 4.5]
Column maxes: [4 5 6]
Column mins: [1 2 3]
